### ISSUE TITLE
Can't authenticate with Mora

### ISSUE THREAD

**Issue by atanasbozhkov** [emicklei/mora#35]
I am trying to bring up an API for my mongoDB instance. 

I currently have a user with read only rules that I can connect with so my mora.properties file looks like this:

```
#listener info is required
http.server.host=0.0.0.0
http.server.port=9123

mongo.db.uri=mongodb://user:pass@localhost:27017/mydb
```

I have also tried the following

```
#listener info is required
http.server.host=0.0.0.0
http.server.port=9123

#Auth 
mongod.mydb.databse=mydb
mongod.mydb.username=user
mongod.mydb.password=pass

mondod.mydb.host=localhost
mondod.mydb.port=27017
```

But when I try to do the following

```
$ curl http://localhost:9123/docs/mydb 
 {
   "success": false,
   "error": {
    "code": 401,
    "name": "unauthorized"
   }
  }
```

And the Mora instance logs:

```
2015/06/20 05:32:00 [mora] connecting to [db=mongodb://user:pass@localhost:27014/mydb] with timeout [0 seconds]
2015/06/20 05:32:00 [mora][error] unauthorized
```

Needless to say - I have checked my user authentication info several times - it is correct.
The thing is - I have tried the exact same URI for mongoDB in another app (node.js mongodb-rest api) and it works, but for some reason Mora fails to authenticate.

Any ideas how to go around that?

**Comment by emicklei** [comment]
As you have probably seen, mora uses the mgo library to connect. 
Then you have probably looked for details here.

Mgo Dial
http://godoc.org/labix.org/v2/mgo#Dial

Mongo URI
http://docs.mongodb.org/manual/reference/connection-string/

In order to reproduce your problem I like to what authorisation you are using and whether you are using collection-level access control.

**Comment by atanasbozhkov** [comment]
@emicklei 
Yes - I have consulted the details from the links.
I am using collection-level access control - "mydb" in the example above should be the only collection that I have access to, so that's why I am providing it in the URI.
What do you mean by "what authorisation"? I was given the credentials (username, password and collection name) by my db admin, I am able to connect via robomongo. What specifically should I ask about?

**Comment by atanasbozhkov** [comment]
I check with the DB Admin - our version of mongoDB is quite old and apparently uses MongoDB Challenge and Response (MONGODB-CR) as an authentication mechanism.
