### ISSUE TITLE
swagger seems doesn't work

### ISSUE THREAD

**Issue by metalwood** [emicklei/mora#39]
![snap](https://cloud.githubusercontent.com/assets/4507840/12480440/4bd43a3a-c07d-11e5-9be7-e6a7b9a87f6a.jpg)

**Comment by emicklei** [comment]
looks like the recent swagger index.html has been changed such that our patches no longer work

**Comment by metalwood** [comment]
I replaced mora/script/patches/index.html with the official swagger index.html, the web page shows much more content but still not the mora's. Do you have any plan to upgrade to the lastest swagger?

**Comment by emicklei** [comment]
sorry for my late response. I am working on it now
