### ISSUE TITLE
resp.WriteHeader(status) in func WriteStatus is not required anymore.

### ISSUE THREAD

**Issue by sapamja** [emicklei/mora#46]
`resp.WriteHeader(status)` in `WriteStatus (response.go)` is not required anymore as `WriteEntity` in go-restful support `WriteHeaderAndEntity`. So, we can use only `resp.WriteHeaderAndEntity(status, r)`

That creates "multiple response.WriteHeader calls" in logs.

**Comment by emicklei** [comment]
thank you for reporting this. I think you are right.

**Comment by emicklei** [comment]
i am working on a fix in https://github.com/emicklei/mora/tree/vendoring

**Comment by sapamja** [comment]
Thanks for the ack.
